// <auto-generated />
using System;
using FoodAdviser.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FoodAdviser.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FoodAdviserDbContext))]
    [Migration("20260204000000_AddRefreshTokens")]
    partial class AddRefreshTokens
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            // NOTE: We delegate to the snapshot for the full model to avoid duplication drift.
            // EF uses this file for migration discovery (MigrationAttribute above).
            // The authoritative model definition is in FoodAdviserDbContextModelSnapshot.
#pragma warning restore 612, 618
        }
    }
}
