// <auto-generated />
using System;
using FoodAdviser.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable enable

namespace FoodAdviser.Infrastructure.Persistence.Migrations;

[DbContext(typeof(FoodAdviserDbContext))]
partial class FoodAdviserDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "9.0.0")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("FoodAdviser.Domain.Entities.FoodItem", b =>
        {
            b.Property<Guid>("Id")
                .HasColumnType("uuid");

            b.Property<DateTimeOffset?>("ExpiresAt")
                .HasColumnType("timestamp with time zone");

            b.Property<string>("Name")
                .IsRequired()
                .HasMaxLength(256)
                .HasColumnType("character varying(256)");

            b.Property<decimal>("Quantity")
                .HasColumnType("numeric(18,4)");

            b.Property<string>("Unit")
                .IsRequired()
                .HasMaxLength(64)
                .HasColumnType("character varying(64)");

            b.HasKey("Id");

            b.HasIndex("Name")
                .IsUnique();

            b.ToTable("food_items", (string)null);
        });

        modelBuilder.Entity("FoodAdviser.Domain.Entities.Receipt", b =>
        {
            b.Property<Guid>("Id")
                .HasColumnType("uuid");

            b.Property<DateTimeOffset>("CreatedAt")
                .HasColumnType("timestamp with time zone");

            b.HasKey("Id");

            b.ToTable("receipts", (string)null);
        });

        modelBuilder.Entity("FoodAdviser.Domain.Entities.Recipe", b =>
        {
            b.Property<Guid>("Id")
                .HasColumnType("uuid");

            b.Property<string>("Description")
                .IsRequired()
                .HasMaxLength(1024)
                .HasColumnType("character varying(1024)");

            b.Property<string>("DishType")
                .IsRequired()
                .HasMaxLength(12)
                .HasColumnType("character varying(12)");

            b.Property<string>("Title")
                .IsRequired()
                .HasMaxLength(256)
                .HasColumnType("character varying(256)");

            b.HasKey("Id");

            b.ToTable("recipes", (string)null);
        });

        modelBuilder.Entity("FoodAdviser.Domain.Entities.Receipt", b =>
        {
            b.OwnsMany("FoodAdviser.Domain.Entities.ReceiptLineItem", "Items", b1 =>
            {
                b1.Property<Guid>("Id")
                    .HasColumnType("uuid");

                b1.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)");

                b1.Property<decimal>("Price")
                    .HasColumnType("numeric(18,2)");

                b1.Property<decimal>("Quantity")
                    .HasColumnType("numeric(18,4)");

                b1.Property<Guid>("ReceiptId")
                    .HasColumnType("uuid");

                b1.Property<string>("Unit")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)");

                b1.HasKey("Id");

                b1.HasIndex("ReceiptId");

                b1.ToTable("receipt_line_items", (string)null);

                b1.WithOwner()
                    .HasForeignKey("ReceiptId");
            });

            b.Navigation("Items");
        });

        modelBuilder.Entity("FoodAdviser.Domain.Entities.Recipe", b =>
        {
            b.OwnsMany("FoodAdviser.Domain.Entities.Ingredient", "Ingredients", b1 =>
            {
                b1.Property<Guid>("RecipeId")
                    .HasColumnType("uuid");

                b1.Property<string>("Name")
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)");

                b1.Property<decimal>("Quantity")
                    .HasColumnType("numeric(18,4)");

                b1.Property<string>("Unit")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)");

                b1.HasKey("RecipeId", "Name");

                b1.ToTable("recipe_ingredients", (string)null);

                b1.WithOwner()
                    .HasForeignKey("RecipeId");
            });

            b.Navigation("Ingredients");
        });
#pragma warning restore 612, 618
    }
}
